version : "3.9"

services:
  backend:
    build: ./backend
    command: python server.py
    ports:
      - "5000:5000"
  
  frontend:
    build: ./server
    command: npm start
    ports:
      - "3000:3000"